name: Java CI with Maven

on: 
  push:
    paths: 
      - "spring_Negomarket/chat-service/**"
  pull_request:
    paths: 
      - "spring_Negomarket/chat-service/**"
  workflow_dispatch:

permissions:
  contents: read

jobs: 
  build: 
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: setup jdk11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: cd spring_Negomarket/chat-service && mvn clean install -DskipTests=true

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-service spring_Negomarket/chat-service

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: dockerhub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-service
