name: Java CI with React

on: 
  push:
    paths:
      - "react_Negomarket/**"
  pull_request:
    paths:
      - "react_Negomarket/**"
  workflow_dispatch:

permissions:
  contents: read

jobs: 
  build: 
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'

    - name: Install Dependences
      run: cd react_Negomarket/ && npm install
      
    - name: Build react app
      run: cd react_Negomarket/ && npm run build

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/negomarket react_Negomarket/

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: dockerhub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/negomarket
